# GitHub Actions 自动构建脚本
name: Webpack Build

on:
  push:
    branches:
      - master

jobs:
    build-to-dist:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
              with:
                  ref: master

            - name: Build and Deploy
              uses: JamesIves/github-pages-deploy-action@master
              env:
                  ACCESS_TOKEN: ${{ secrets.ACTION_TOKEN }}
                  BASE_BRANCH: master
                  BRANCH: gh-pages
                  FOLDER: dist
                  BUILD_SCRIPT: npm install && npm run build-lib && npm run build